# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2fc9590c-e366-478b-b37f-aff19a493d9f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2fc9590c-e366-478b-b37f-aff19a493d9f".device = "/dev/disk/by-uuid/2fc9590c-e366-478b-b37f-aff19a493d9f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C214-25FA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d54ce8a7-14cf-4eed-a121-aab6d88d82a6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
