keys:
  - &admin_ben age1uml684typ6yj5n6sps8fzccndt206ve6kr8yaavlrgzguj7993psxwqenx
  - &server_rooster age1ccz8dmr2fdfy7k3jfyuc9dl0a6x8ju6r6c2c49prvnu6wqmnxd5qqcjne4
  - &server_pine age1qp4kpmxszz0g7gsm962s9f95avhgtu2rhls5245zkjh64cysncwsahjzsw
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_ben
          - *server_rooster
          - *server_pine
